#!/bin/sh

#
# Lists all MPD albums and artists in dmenu and plays the selected
#

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU='dmenu -i'
fi

artist=`mpc list artist`
album=`mpc list album`

result=`echo "$album $artist" |  $DMENU`
[[ -n "$result" ]] && mpc clear && mpc add "$result" && mpc play
