#!/bin/bash
result=`printf "shutdown\nreboot\nsuspend" | dmenu`
case $result in
    shutdown)
        sudo shutdown -h now
        ;;
    reboot)
        sudo reboot
        ;;
    suspend)
		xscreensaver-command -lock
        sudo pm-suspend
		XAUTHORITY=$(ps -C xinit -f --no-header | sed -n 's/.*-auth //; s/ -[^ ].*//; p') xset -display :0 dpms force on 
        ;;
    *)
        ;;
    esac
