#!/bin/bash

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU='dmenu -i'
fi

result=`printf "shutdown\nreboot\nsuspend" | eval $DMENU`
case $result in
    shutdown)
        sudo shutdown -h now
        ;;
    reboot)
        sudo reboot
        ;;
    suspend)
		sudo systemctl suspend
        ;;
    *)
        ;;
    esac
