#!/bin/sh

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU='dmenu -i'
fi

xrandr_out=`xrandr`
avail_modes=`echo "$xrandr_out" | grep -P "   *[0-9]+x[0-9]+" | awk '{print $1}'`
mode=`echo "$avail_modes" | eval $DMENU -p 'resolution'`
output=`xrandr | grep " connected" | awk '{print $1}'`
xrandr --output $output --mode "$mode"
