#!/bin/bash
if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU='dmenu -i'
fi
term=`echo | eval $DMENU -p 'Solve'`
result=`echo $term | bc -l`

#term=`echo | eval $DMENU -p 'Solve'`
#result=`python -c "print($term)"`

notify-send -u normal -a "Solve" "$term" "$result"
echo "$result" | xclip -selection "clipboard" -i
