#!/bin/bash
# Lists current mpd playlist in vertical dmenu and play the chosen song

if [ -f $HOME/.dmenurc ]; then
	. $HOME/.dmenurc
else
	DMENU='dmenu -i'
fi

song=`mpc playlist | $DMENU -l 10`

# Add trailing numbers and grep it to give mpc an id to play
number=`mpc playlist | awk '{print NR, $0}' | grep "$song" | awk '{print $1}'`

# When nothing is selected $number will be something like "1 2 3 4 5 6 7 8 ...", so we simply test if we have ONE number
[[ "$numer" -ge 0 ]] && mpc play "$number"
