#!/bin/bash

#
# Lists "all" regular files in current pwd and pipes to input. Opens the
# selected file with xdg-open.
#
# Depends on File-MimeInfo (http://search.cpan.org/dist/File-MimeInfo/)
# for better mime identification
# On Arch:
#   pacman -S perl-file-mimeinfo
#

if [ -f $HOME/.dmenurc ]; then
    . $HOME/.dmenurc
else
    DMENU_VERT='dmenu -i'
fi

# whitelist filetypes
filetypes="(sh|py|java|mp3|ogg|jpeg|jpg|png|gif|tex|pdf)"

if [ -z "$1" ]; then
    dir="."
else
    dir="$1/"
fi

files=$(find $dir -type f -regextype "posix-extended" -iregex "\.[/a-z0-9]*(\.$filetypes)?" -not -iregex '.*\.(git|svn|hg).*')
echo "Found "$(echo "$files" | wc -l)" files."
result=$(echo "$files" | eval $DMENU_VERT -p open)
if [ ! -z "$result" ]; then
    mime=$(mimetype -b "$result")
    app=$(xdg-mime query default "$mime")
    echo "Open $result ($mime) with $app."
    xdg-open "$result"
fi
