#!/bin/bash

SESSION="ossim-dev"
DIR="/home/jln/Code/C++/omnetpp/ossim"

tmux has-session -t $SESSION 2>/dev/null

if [ "$?" -eq 1 ] ; then

    tmux new-session -d -s $SESSION
    tmux rename-window "dev"
    tmux send-keys "cd $DIR/src" "C-m" "C-l"
    tmux send-keys "vim tree/multitree" "C-m"

    tmux split-window -h -p 40
    tmux send-keys "cd $DIR" "C-m" "C-l"
    tmux send-keys "./build-jul.sh && cd simulations && ../src/so -r 0 -n .:../src:../../inet/examples:../../inet/src -l ../../inet/src/inet Multitree.ini -c Multitree_Network; cd .."

    tmux select-pane -t 0

    tmux new-window -n "results"
    tmux send-keys "cd $DIR/simulations/results" "C-m" "C-l"

    tmux new-window -n "visual"
    tmux send-keys "cd $DIR/simulations/" "C-m" "C-l"

    tmux new-window -n "git"
    tmux send-keys "cd $DIR" "C-m" "C-l"

    tmux select-window -t 1
fi

tmux attach-session -t $SESSION
