#!/bin/bash

SESSION="$1-dev"
IPY=${2:-ipython}

tmux has-session -t $SESSION 2>/dev/null

if [ "$?" -eq 1 ] ; then

    tmux new-session -d -s $SESSION
    tmux rename-window "dev"
    tmux send-keys "workon $1" "C-m"

    tmux split-window -h
    tmux send-keys "workon $1" "C-m"
    tmux send-keys "$IPY manage.py" "C-m"

    tmux split-window -v -t 1
    tmux send-keys "workon $1" "C-m" "C-l"

    tmux select-pane -t 0
    tmux send-keys "vim ." "C-m"

    tmux new-window -n "server"
    tmux send-keys "workon $1" "C-m"
    tmux send-keys "python manage.py runserver" "C-m"
    tmux select-window -t 1
fi

tmux attach-session -t $SESSION
