#!/bin/bash

# TODO session names have constraints (no leading dot, etc...)

SESSION=$(basename `pwd`)

tmux has-session -t $SESSION 2>/dev/null

if [ "$?" -eq 1 ] ; then

    tmux new-session -d -s $SESSION
    tmux rename-window "dev"
    tmux send-keys "fo" "C-m"

    tmux new-window -n "git"

    tmux select-window -t 1
    tmux select-pane -t 1
fi

tmux attach-session -t $SESSION
