#! /bin/sh

bspc monitor -d term www dev misc irc 6 7 8
#bspc monitor -d T W D M I 6 7 8

# set monocle layout for browser workspace
bspc desktop ^2 -l monocle

bspc config border_width           2
bspc config window_gap             20
bspc config split_ratio            0.50
bspc config focus_follows_pointer  false
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config auto_cancel            true
bspc config auto_alternate         false
bspc config ignore_ewmh_focus      true

#bspc config focused_border_color          "#917154"
#bspc config focused_border_color          "#BF3F34"
bspc config focused_border_color          "#989584"
bspc config normal_border_color           "#121212"
bspc config urgent_border_color           "#EF545F"
bspc config presel_border_color           "#705D22"
bspc config focused_private_border_color  "#88a1ba"
bspc config active_private_border_color   "#88a1ba"
bspc config normal_private_border_color   "#627a92"

bspc rule -a Chromium desktop=^2
bspc rule -a Firefox desktop=^2
bspc rule -a Eclipse desktop=^3
bspc rule -a Gimp desktop=^4
bspc rule -a feh floating=true focus=false borderless=true
bspc rule -a sxiv floating=true
bspc rule -a mplayer floating=true
bspc rule -a ncmpcpp floating=true
bspc rule -a Steam desktop=^4 follow=true fullscreen=true

numlockx &
compton -c -C -G -f -D 3 -t 0 &
firefox &

urxvtc &
xset m 2 0 &

xsetroot -cursor_name left_ptr &
unclutter -idle 3 &
tint2 &

xscreensaver -no-splash &
dropbox start &

xcmenu --daemon &

#(sleep 1 && /home/jln/.config/bspwm/panel) &
/home/jln/.config/bspwm/panel &
