#! /bin/sh
bspc config border_width 1
bspc config window_gap 10
bspc config bottom_padding 0
bspc config top_padding 0
bspc config split_ratio 0.50
bspc config focus_follows_pointer false
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config auto_cancel true
bspc config auto_alternate false
bspc config ignore_ewmh_focus true

# bspc config focused_border_color "#fdf6e3"
bspc config focused_border_color "#909090"
bspc config normal_border_color "#121212"
bspc config urgent_border_color "#EF545F"
bspc config presel_border_color "#705D22"
bspc config focused_private_border_color "#88a1ba"
bspc config active_private_border_color "#88a1ba"
bspc config normal_private_border_color "#627a92"
bspc config presel_feedback_color "#121212"
bspc monitor -d term www dev misc msg 6 7 8

# set monocle layout for browser workspace
bspc desktop www -l monocle
bspc desktop dev -l monocle

bspc rule -a Pavucontrol state=floating
bspc rule -a Chromium desktop=^2
bspc rule -a Firefox desktop=^2
bspc rule -a Eclipse desktop=^3
bspc rule -a jetbrains-idea-ce desktop=^3  # intellij 'did you know' popup
bspc rule -a jetbrains-idea-c desktop=^3  # the rest of intellij
bspc rule -a Gimp desktop=^4
bspc rule -a Steam desktop=^4 border=off
bspc rule -a Skype desktop=^5
bspc rule -a Mendeleydesktop.x86_64 desktop=^4
bspc rule -a libreoffice-startcenter desktop=^4
bspc rule -a Zathura state=tiled

bspc rule -a scratchpad sticky=on state=floating

#
# Autostart
#
/home/jln/.config/bspwm/panel &
urxvtc -e htop &
bspc window -t private
tint2 &
xsetroot -cursor_name left_ptr &
xcmenu --daemon &
xscreensaver -no-splash &
~/.bin/java_nonreparenting_wm_hack.sh &
dunst &
unclutter -idle 3 &
auto-xflux &

~/.bin/autostart.local.sh
