#! /bin/sh
#
# Example panel for dzen2

source /home/jln/.config/bspwm/panel_colors

adaptive_centering=0
screen_width=$(sres -W)
NORMIFS=$IFS
FIELDIFS=':'
PADDING=' '

while getopts 'af:s:' opt ; do
    case "$opt" in
        a)
            adaptive_centering=1
            ;;
        f)
            font_family=$OPTARG
            ;;
        s)
            font_size=$OPTARG
            ;;
    esac
done

shift $((OPTIND - 1))

while read -r line ; do
    case $line in
        C*)
            # conky output
            sys_infos="${PADDING}${line#?}${PADDING}${PADDING}"
            ;;

        W*)
            # bspwm internal state
            wm_infos="$PADDING"
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        # desktops
                        name=${item#?}
                        print=true
                        case $item in
                            O*)
                                # focused occupied desktop
                                FG=$COLOR_FOCUSED_OCCUPIED_FG
                                ;;
                            F*)
                                # focused free desktop
                                FG=$COLOR_FOCUSED_FREE_FG
                                ;;
                            U*)
                                # focused urgent desktop
                                FG=$COLOR_FOCUSED_URGENT_FG
                                ;;
                            o*)
                                # occupied desktop
                                FG=$COLOR_OCCUPIED_FG
                                #title="^ro(8x8)"
                                ;;
                            f*)
                                # free desktop
                                FG=$COLOR_FREE_FG
                                #print=false
                                ;;
                            u*)
                                # urgent desktop
                                FG=$COLOR_URGENT_FG
                                BG=$COLOR_URGENT_BG
                                ;;
                        esac
                        if  $print ; then
                            wm_infos="${wm_infos}^fg(${FG})^bg(${BG})^ca(1, bspc desktop -f ${name})^ca(2, bspc window -d ${name})${PADDING}${name}${PADDING}^ca()^ca()^fg()"
                        fi
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac

    set -- $(printf '%s\0%s' "$wm_infos" "$sys_infos" | sed 's/\^[a-z]\+([^)]*)//g' | xargs -0 txtw -f "$font_family" -s "$font_size")

    left_width=$1
    right_width=$2

    left_indent=0
    right_indent=$((screen_width - right_width - 65))

    printf "%s\n" "^pa($left_indent)$wm_infos^pa($right_indent)$sys_infos"

done
