#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

PANEL_HEIGHT=20
bspc config top_padding $PANEL_HEIGHT

# for bottom panel
#bspc config bottom_padding $PANEL_HEIGHT
#SCREEN_HEIGHT=$(sres -H)
#PANEL_Y=$SCREEN_HEIGHT-$PANEL_HEIGHT
PANEL_Y=0

bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
conky -c ~/.conkyrc-bspwm > "$PANEL_FIFO" &
clock -sf 'S%a  %d.%m  %H:%M' > "$PANEL_FIFO" &

source /home/jln/.config/bspwm/panel_colors

FONT_FAMILY='termsyn'
FONT_SIZE=11
cat "$PANEL_FIFO" | /home/jln/.config/bspwm/panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" -y $PANEL_Y &

wait
