#! /bin/sh
if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

PANEL_HEIGHT=14

# top panel
PANEL_Y=0
bspc config top_padding $((PANEL_HEIGHT+PANEL_Y))

# bottom panel
#SCREEN_HEIGHT=$(sres -H)
#PANEL_Y=$SCREEN_HEIGHT-$PANEL_HEIGHT
#bspc config bottom_padding $PANEL_HEIGHT

bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'X%s' > "$PANEL_FIFO" &
clock -s -i 30 -f "T%a %d.%m  %H:%M" > "$PANEL_FIFO" &
conky -c ~/.conkyrc > "$PANEL_FIFO" &

source /home/jln/.config/bspwm/panel_colors

FONT_FAMILY='tamzen'
FONT_SIZE=10
cat "$PANEL_FIFO" | /home/jln/.config/bspwm/panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FG" -bg "$COLOR_BG" -y $PANEL_Y &

wait
